# Generated by Django 3.2.5 on 2023-12-25 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currentIdentity',
            field=models.CharField(max_length=10, null=True, verbose_name='求职者身份'),
        ),
        migrations.CreateModel(
            name='CommentJobs',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobs', verbose_name='职位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论列表',
                'db_table': 'comment',
            },
        ),
    ]
