create database ods_jobfree;

CREATE TABLE `ods_jobfree`.`ods_jobfree_db_spider_t_jobs` (
  `job_id` int,
  `abroadFlag` string ,
  `abroadTipInfo` string ,
  `alreadyCallPhone` string ,
  `applyType` string ,
  `campusBestCompany` string ,
  `campusRootOrgInfo` string ,
  `canBeRegular` string ,
  `canRemoteInternship` string ,
  `cardCustomJson` string ,
  `cardType` string ,
  `chatWindow` string ,
  `cityDistrict` string ,
  `cityId` string ,
  `companyId` string ,
  `companyLogo` string ,
  `companyName` string ,
  `companyNumber` string ,
  `companyRootId` string ,
  `companyScaleTypeTagsNew` string ,
  `companySize` string ,
  `companyUrl` string ,
  `deliveryPath` string ,
  `displayPhoneNumber` string ,
  `distance` string ,
  `distanceFormat` string ,
  `education` string ,
  `extensions` string ,
  `featureServer` string ,
  `feedOperation` string ,
  `feedPosition` string ,
  `financingStage` string ,
  `firstPublishTime` string ,
  `hasAppliedPosition` string ,
  `industryCompanyTags` string ,
  `industryName` string ,
  `internshipMonths` string ,
  `isNewPosition` string ,
  `jobId` string ,
  `jobSummary` string ,
  `liveCard` string ,
  `matchInfo` string ,
  `menVipLevel` string ,
  `name` string ,
  `needMajor` string ,
  `number` string ,
  `orgBestEmployerFlag` string ,
  `orgPayedFlag` string ,
  `organizer` string ,
  `positionCommercialLabel` string ,
  `positionExpandCardData` string ,
  `positionExpandCardType` string ,
  `positionHighlight` string ,
  `positionOfNlp` string ,
  `positionSourceType` string ,
  `positionSourceTypeUrl` string ,
  `positionUrl` string ,
  `property` string ,
  `propertyCode` string ,
  `propertyType` string ,
  `propertyTypeUrl` string ,
  `provideInternshipCertificate` string ,
  `proxyModel` string ,
  `publishTime` string ,
  `recallSign` string ,
  `recruitNumber` string ,
  `redirectUrl` string ,
  `redirectable` string ,
  `rootCompanyNumber` string ,
  `rpoProxied` string ,
  `rpoProxy` string ,
  `salary60` string ,
  `salaryCount` string ,
  `salaryReal` string ,
  `salaryType` string ,
  `settlementType` string ,
  `showDistance` string ,
  `skillLabel` string ,
  `skillLabelPersonality` string ,
  `staffCard` string ,
  `streetId` string ,
  `streetName` string ,
  `subJobTypeLevel` string ,
  `subJobTypeLevelName` string ,
  `tagABC` string ,
  `tradingArea` string ,
  `volcanoMeterial` string ,
  `weeklyInternshipDays` string ,
  `welfareLabel` string ,
  `welfareTagList` string ,
  `workCity` string ,
  `workDateType` string ,
  `workMode` string ,
  `workType` string ,
  `workingExp` string ,
  `local_row_update_time` timestamp,
  `cdc_sync_date` timestamp
) PARTITIONED BY (partition_date string);
CREATE TABLE `ods_jobfree`.`ods_jobfree_db_jobfree_t_resume` (
  `id` string,
  `eduHighestLevel` int,
  `eduHighestLevelTranslation` string,
  `workingexpCode` int,
  `workingexp` string,
  `worktypeCode` int,
  `worktype` string,
  `workcity` int,
  `workcityTranslation` string,
  `workcity2` int,
  `workcity2Translation` string,
  `workcity3` int,
  `workcity3Translation` string,
  `subjobtypelevel` bigint,
  `subjobtypelevelname` string,
  `skilllabel` string,
  `propertycode` int,
  `property` string,
  `preferredSalaryMin` int,
  `preferredSalaryMax` int,
  `SelfEvaluate` string,
  `created_time` timestamp,
  `last_update` timestamp,
  `user_id` int,
  `cdc_sync_date` timestamp
) PARTITIONED BY (partition_date string);

CREATE TABLE `ods_jobfree`.`ods_jobfree_db_jobfree_t_clickjobs` (
  `cid` string,
  `count` int,
  `created_time` timestamp,
  `last_update` timestamp,
  `job_id` int,
  `user_id` int,
  `cdc_sync_date` timestamp
) PARTITIONED BY (partition_date string);

CREATE TABLE `ods_jobfree`.`ods_jobfree_db_jobfree_t_starjobs` (
  `sid` string,
  `created_time` timestamp,
  `job_id` int,
  `user_id` int,
  `cdc_sync_date` timestamp
) PARTITIONED BY (partition_date string);